name: Remote BUILD and DEPLOY

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push to EC2 and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SECRET_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22

          script: |
            cd ~
            chmod +x deploy.sh
            ./deploy.sh